- name: install haproxy
  package:
    name: "haproxy"
    state: present
  register: haproxystatus
- name: configure haproxy
  template:
    dest: /etc/haproxy/haproxy.cfg
    src: "../configs/{{ world }}/conf/haproxy.cfg"
- name: haproxy service start
  service:
    name: "haproxy"
    state: restarted